class CountryNamesList {
  List<String> countriesWithCurrency = [
    "Afghanistan | AFN ؋",
    "Albania | ALL Lekë",
    "Algeria | DZD د.ج",
    "Andorra | EUR €",
    "Angola | AOA Kz",
    "Antigua and Barbuda | XCD \$",
    "Argentina | ARS \$",
    "Armenia | AMD ֏",
    "Australia | AUD \$",
    "Austria | EUR €",
    "Azerbaijan | AZN ₼",
    "Bahamas | BSD \$",
    "Bahrain | BHD BD",
    "Bangladesh | BDT ৳",
    "Barbados | BBD \$",
    "Belarus | BYN Br",
    "Belgium | EUR €",
    "Belize | BZD ",
    "Benin∣XOFCFA",
    "Bhutan∣BTNNu.",
    "Bolivia∣BOBBs.",
    "BosniaandHerzegovina∣BAMKM",
    "Botswana∣BWPPula",
    "Brazil∣BRLR",
    "Brunei | BND \$",
    "Bulgaria | BGN лв",
    "Burkina Faso | XOF CFA",
    "Burundi | BIF Fr",
    "Cabo Verde | CVE \$",
    "Cambodia | KHR ៛",
    "Cameroon | XAF CFA",
    "Canada | CAD \$",
    "Central African Republic | XAF CFA",
    "Chad | XAF CFA",
    "Chile | CLP \$",
    "China | CNY ¥",
    "Colombia | COP \$",
    "Comoros | KMF KMF",
    "Congo | XAF CFA",
    "Costa Rica | CRC ₡",
    "Cote d'Ivoire | XOF CFA",
    "Croatia | HRK kn",
    "Cuba | CUP \$MN",
    "Cyprus | EUR €",
    "Czech Republic | CZK Kč",
    "Democratic Republic of the Congo | XAF CFA",
    "Denmark | DKK kr",
    "Djibouti | DJF Fr",
    "Dominica | XCD ",
    "DominicanRepublic∣DOPRD",
    "Ecuador | USD \$",
    "Egypt | EGP ج.م",
    "El Salvador | USD\$",
    "Equatorial Guinea | XAF CFA",
    "Eritrea | ERN ናቕፋ",
    "Estonia | EUR €",
    "Eswatini | SZL E",
    "Ethiopia | ETB Br",
    "Fiji | FJD \$",
    "Finland | EUR €",
    "France | EUR €",
    "Gabon | XAF CFA",
    "Gambia | GMD D",
    "Georgia | GEL ₾",
    "Germany | EUR €",
    "Ghana | GHS GH¢",
    "Greece | EUR €",
    "Grenada | XCD \$",
    "Guatemala | GTQ Q",
    "Guinea | GNF FG",
    "Guinea-Bissau | XOF CFA",
    "Guyana | GYD ",
    "Haiti∣HTGGourdes",
    "Honduras∣HNLL",
    "Hungary∣HUFFt",
    "Iceland∣ISKkr",
    "India∣INR₹",
    "Indonesia∣IDRRp",
    "Iran∣IRRریال",
    "Iraq∣IQDع.د",
    "Ireland∣EUR€",
    "Israel∣ILS₪",
    "Italy∣EUR€",
    "Jamaica∣JMDJ",
    "Japan | JPY ¥",
    "Jordan | JOD JD",
    "Kazakhstan | KZT ₸",
    "Kenya | KES KSh",
    "Kiribati | AUD \$",
    "Kuwait | KWD KD",
    "Kyrgyzstan | KGS  сом",
    "Laos | LAK ₭",
    "Latvia | EUR €",
    "Lebanon | LBP £L",
    "Lesotho | LSL L",
    "Liberia | LRD \$",
    "Libya | LYD LD",
    "Liechtenstein | CHF Fr",
    "Lithuania | EUR €",
    "Luxembourg | EUR €",
    "Madagascar | MGA Ariary",
    "Malawi | MWK MK",
    "Malaysia | MYR RM",
    "Maldives | MVR .ރ",
    "Mali | XOF CFA",
    "Malta | EUR €",
    "Marshall Islands | USD \$",
    "Mauritania | MRU UM",
    "Mauritius | MUR Rs",
    "Mexico | MXN \$",
    "Micronesia | USD ",
    "Moldova∣MDLLei",
    "Monaco∣EUR€",
    "Mongolia∣MNT₮",
    "Montenegro∣EUR€",
    "Morocco∣MADدرهم",
    "Mozambique∣MZNMT",
    "Myanmar∣MMKKs",
    "Namibia∣NADN",
    "Nauru | AUD \$",
    "Nepal | NPR रु",
    "Netherlands | EUR €",
    "New Zealand | NZD ",
    "Nicaragua∣NIOC",
    "Niger | XOF CFA",
    "Nigeria | NGN ₦",
    "North Korea | KPW ₩",
    "North Macedonia | MKD ден",
    "Norway | NOK kr",
    "Oman | OMR ريال عماني",
    "Pakistan | PKR Rs.",
    "Palau | USD \$",
    "Panama | USD \$",
    "Papua New Guinea | PGK K",
    "Paraguay | PYG Gs.",
    "Peru | PEN S/.",
    "Philippines | PHP ₱",
    "Poland | PLN zł",
    "Portugal | EUR €",
    "Qatar | QAR ر.ق",
    "Romania | RON lei",
    "Russia | RUB ₽",
    "Rwanda | RWF Frw",
    "Saint Kitts and Nevis | XCD \$",
    "Saint Lucia | XCD \$",
    "Saint Vincent and the Grenadines | XCD \$",
    "Samoa | WST ៕",
    "San Marino | EUR €",
    "Sao Tome and Principe | STN Db",
    "Saudi Arabia | SAR ر.س",
    "Senegal | XOF CFA",
    "Serbia | RSD din.",
    "Seychelles | SCR SCR",
    "Sierra Leone | SLL Le",
    "Singapore | SGD \$",
    "Slovakia | EUR €",
    "Slovenia | EUR €",
    "Solomon Islands | SBD \$",
    "Somalia | SOS Sh. So.",
    "South Africa | ZAR R",
    "South Korea | KRW ₩",
    "South Sudan | SSP SSP",
    "Spain | EUR €",
    "Sri Lanka | LKR රු",
    "Sudan | SDG SDG",
    "Suriname | SRD \$",
    "Sweden | SEK kr",
    "Switzerland | CHF Fr",
    "Syria | SYP £S",
    "Tajikistan | TJS ₽",
    "Tanzania | TZS Tsh",
    "Thailand | THB ฿",
    "Timor-Leste | USD ",
    "Togo∣XOFCFA",
    "Tonga∣TOPT",
    "Trinidad and Tobago | TTD TT\$",
    "Tunisia | TND DT",
    "Turkey | TRY ₺",
    "Turkmenistan | TMT m",
    "Tuvalu | AUD \$",
    "Uganda | UGX UGX",
    "Ukraine | UAH ₴",
    "United Arab Emirates | AED AED",
    "United Kingdom | GBP £",
    "United States | USD \$",
    "Uruguay | UYU \$U",
    "Uzbekistan | UZS 🇺🇿",
    "Vanuatu | VUV VT",
    "Vatican City | EUR €",
    "Venezuela | VES Bs.",
    "Vietnam | VND ₫",
    "Yemen | YER ر.ي",
    "Zambia | ZMK ZMK",
    "Zimbabwe | ZWL \$",
  ];
}
