// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgLzn4AFBZdr5Jz-3qm-ZjA3sLeIa1Y-c',
    appId: '1:878134600527:web:85e46998a0ddae07631b3a',
    messagingSenderId: '878134600527',
    projectId: 'alisports',
    authDomain: 'alisports.firebaseapp.com',
    storageBucket: 'alisports.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjrlLZ65oqEr3Q3yrA2ciaz_tPKUJLxxc',
    appId: '1:878134600527:android:7e6a74797d8545cb631b3a',
    messagingSenderId: '878134600527',
    projectId: 'alisports',
    storageBucket: 'alisports.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv_SBq1MhbWkyzJB9o9O_1p7xGCP8ocdg',
    appId: '1:878134600527:ios:b75bd7bd3b9cbd72631b3a',
    messagingSenderId: '878134600527',
    projectId: 'alisports',
    storageBucket: 'alisports.firebasestorage.app',
    iosBundleId: 'com.example.alisportspk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCv_SBq1MhbWkyzJB9o9O_1p7xGCP8ocdg',
    appId: '1:878134600527:ios:0a0f3b09b4886644631b3a',
    messagingSenderId: '878134600527',
    projectId: 'alisports',
    storageBucket: 'alisports.firebasestorage.app',
    iosBundleId: 'com.alisports.pk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgLzn4AFBZdr5Jz-3qm-ZjA3sLeIa1Y-c',
    appId: '1:878134600527:web:547e3390d642589d631b3a',
    messagingSenderId: '878134600527',
    projectId: 'alisports',
    authDomain: 'alisports.firebaseapp.com',
    storageBucket: 'alisports.firebasestorage.app',
  );
}
