import 'package:alisportspk/datamodels/productInfo.dart';

final List<Productinfo> Saleitems = [
  Productinfo(
    image: "assets/images/armguard.png",
    image2: "assets/images/armguard.png",
    title: "CA Gold Cricket Arm Guard",
    brand: "CA",
    textualPrice: "Rs.1,450.00 PKR",
    price: 1450.00,
    mainCategory: "cricket others",
    subCategory: "leg wear",
    size: "Large",
    discount: 25.0,
    quantity: 25,
  ),
  Productinfo(
    image: "assets/images/saleItem7-removebg-preview.png",
    image2: "assets/images/saleItem7_1-removebg-preview.png",
    title: "CA Kamo Cricket Shoes",
    brand: "CA",
    textualPrice: "Rs.6,500.00 PKR",
    price: 6500.00,
    mainCategory: "cricket shoes",
    discount: 25.0,
    quantity: 25,
  ),
  Productinfo(
    image: "assets/images/saleItem1_1-removebg-preview.png",
    image2: "assets/images/saleItem1_2-removebg-preview.png",
    title: "Summer Sports V2 T-Shirt",
    brand: "Psl",
    textualPrice: "Rs.1,450.00 PKR",
    price: 1450.00,
    mainCategory: "cricket t-shirt",
    discount: 11.0,
    quantity: 25,
  ),
  Productinfo(
    image: "assets/images/saleItem2_1-removebg-preview.png",
    image2: "assets/images/saleItem2_2-removebg-preview.png",
    title: "Summer Sports V3 T-Shirt",
    brand: "Psl",
    textualPrice: "Rs.1,450.00 PKR",
    price: 1450.00,
    mainCategory: "cricket t-shirt",
    discount: 22.0,
    quantity: 25,
  ),
  Productinfo(
    image: "assets/images/saleItem3_1-removebg-preview.png",
    image2: "assets/images/saleItem3_2-removebg-preview.png",
    title: "Summer Sports V4 T-Shirt",
    brand: "Psl",
    textualPrice: "Rs.1,490.00 PKR",
    price: 1490.00,
    mainCategory: "cricket t-shirt",
    discount: 19.0,
    quantity: 25,
  ),
  Productinfo(
    image: "assets/images/saleItem4_1-removebg-preview.png",
    image2: "assets/images/saleItem4_2-removebg-preview.png",
    title: "Dual Tone Dry Sports T-Shirt",
    brand: "Psl",
    textualPrice: "Rs.1,490.00 PKR",
    price: 1490.00,
    mainCategory: "cricket t-shirt",
    discount: 16.0,
    quantity: 25,
  ),
  Productinfo(
    image: "assets/images/saleItem5_1-removebg-preview.png",
    image2: "assets/images/saleItem5_2-removebg-preview.png",
    title: "Dual Tone Dry Sports V2 T-Shirt",
    brand: "Psl",
    textualPrice: "Rs.1,490.00 PKR",
    price: 1490.00,
    mainCategory: "cricket t-shirt",
    discount: 25.0,
    quantity: 25,
  ),
  Productinfo(
    image: "assets/images/saleItem8_1-removebg-preview.png",
    image2: "assets/images/saleItem8-removebg-preview.png",
    title: "CA PRO Boost Cricket Shoes",
    brand: "CA",
    textualPrice: "Rs.1,550.00 PKR",
    price: 1550.00,
    mainCategory: "cricket t-shirt",
    discount: 25.0,
    quantity: 25,
  ),
  Productinfo(
    image: "assets/images/saleItem6_1-removebg-preview.png",
    image2: "assets/images/saleItem6_2-removebg-preview.png",
    title: "Dual Tone Dry Sports V8 T-Shirt",
    brand: "Psl",
    textualPrice: "Rs.1,490.00 PKR",
    price: 1490.00,
    mainCategory: "cricket t-shirt",
    discount: 20.0,
    quantity: 25,
  ),
  Productinfo(
    image: "assets/images/chestGuard.png",
    image2: "assets/images/chestguard2.png",
    title: "CA Plus Cricket chest Guard",
    brand: "CA",
    textualPrice: "Rs.1,950.00 PKR",
    price: 1950.00,
    mainCategory: "cricket",
    discount: 12.0,
    quantity: 25,
  ),
  Productinfo(
    image: "assets/images/cricket_helmet.png",
    image2: "assets/images/crickethelmet2.png",
    title: "CA Plus Cricket Helmet",
    brand: "CA",
    textualPrice: "Rs.4,500.00 PKR",
    price: 4500.00,
    mainCategory: "cricket",
    discount: 19.0,
    quantity: 25,
  ),
  Productinfo(
    image: "assets/images/thighGuard.png",
    image2: "assets/images/thightguard3.png",
    title: "CA Performance 15000 Thigh Pad",
    brand: "CA",
    textualPrice: "Rs.5,450.00 PKR",
    price: 5450.00,
    mainCategory: "cricket",
    discount: 25.0,
    quantity: 25,
  ),
  Productinfo(
    image: "assets/images/thighguard2.png",
    image2: "assets/images/thighguard4.png",
    title: "CA Performance 10000 Thigh Pad",
    brand: "CA",
    textualPrice: "Rs.4,650.00 PKR",
    price: 4650.00,
    mainCategory: "cricket",
    discount: 25.0,
    quantity: 25,
  ),
  Productinfo(
    image: "assets/images/shoes.png",
    image2: "assets/images/shoes2.png",
    title: "CA Kamo Cricket Shoes",
    brand: "CA",
    textualPrice: "Rs.6,500.00 PKR",
    price: 6500.00,
    mainCategory: "cricket",
    discount: 18.0,
    quantity: 25,
  ),
  Productinfo(
    image: "assets/images/rollerStick2.png",
    image2: "assets/images/rollerStick.png",
    title: "Deep Tissue Muscle Massage Roller Stick for Pain Relief & Recovery",
    brand: "ALI SPORTS",
    textualPrice: "Rs.1,550.00 PKR",
    price: 1550.00,
    mainCategory: "massage",
    discount: 14.0,
    quantity: 25,
  ),
  Productinfo(
    image: "assets/images/yogaball.png",
    image2: "assets/images/yogaball2.png",
    title: "Anti-Burst Exercise Gym Ball for Yoga & Fitness",
    brand: "ALI SPORTS",
    textualPrice: "Rs.1,850.00 PKR",
    price: 1850.00,
    mainCategory: "exercise",
    discount: 25.0,
    quantity: 25,
  ),
];
